version: '3.8'

services:
  zorin:
    build: .
    container_name: zorin-desktop
    restart: unless-stopped
    volumes:
      - zorin-data:/home/zorin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zorin.rule=Host(`yourwebsitehere.com`)"
      - "traefik.http.routers.zorin.entrypoints=websecure"
      - "traefik.http.routers.zorin.tls.certresolver=letsencrypt"
      - "traefik.http.services.zorin.loadbalancer.server.port=8080"
    environment:
      - VNC_PASSWORD=changeme

volumes:
  zorin-data:
